// import { Head } from "next/document";
// export const metadata = {
//     title: "Add Your Blog",
//     description: "Generated by create next app",
//   };
export async function generateMetadata(){
    return {
        title: "Add Your Blog",
        description: "Generated by create next app",
    }
}
export default function Page() {
    return (
        <section>
            <h1 className="text-4xl font-bold text-center my-10">Add Your Blog Post</h1>
        </section>
    );
}