// 'use client'
import { headers } from "next/headers";
// import { usePathname } from "next/navigation";
import ServerComponent from "./ServerComponent";



export async function generateMetadata() {
    
    return {
        title: "Add Your Blog",
        description: "Generated by create next app",
    }
}


// export const metadata = {
//     title: "Add Your Blog",
//     description: "Explore world with lot of memories",
// };

export default function AddBlog({}) {
    // const headerList = headers();
    // const domain = headerList.get("referer")
    // const pathName = domain.split("/")
    // console.log(pathName[3]);
    
    return (
        <section>
            <h1 className="text-4xl font-bold text-center my-10">Add Your Blog Post</h1>
            {/* <ServerComponent></ServerComponent> */}
        </section>
    );
}