import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./navbar";
// import NavBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <head>
        <link rel="icon" href="https://i.ibb.co/f9g36Zz/exploresphere-high-resolution-logo-transparent-1.png"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poetsen+One&display=swap" rel="stylesheet" />
        <title>ExploreSphere</title>
      </head>
      <body className={inter.className}>
        <NavBar></NavBar>

        {children}
      </body>
    </html>
  );
}
