
import Image from "next/image";
import Banner from "./components/banner/Banner";
import Lifestyle from "./components/lifestyle/Lifestyle";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <div>
      </div>
      <Banner></Banner>
      <Lifestyle></Lifestyle>
    </>
  );
}
